-- LEGACY SNAPSHOT: no aplicar en entornos nuevos ni usar como fuente de verdad.
-- Las migraciones versionadas en supabase/migrations/ son la fuente de verdad.
-- Este archivo se conserva temporalmente para comparar instalaciones académicas previas.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  brand text not null, name text not null, gender text not null check (gender in ('hombre','mujer','unisex')),
  category text not null default 'diseñador' check (category in ('diseñador','nicho')),
  size_ml integer not null check (size_ml > 0), price numeric(12,2) not null check (price >= 0), stock integer not null default 0 check (stock >= 0),
  intensity integer not null check (intensity between 1 and 5), family text not null, top_notes text not null, heart_notes text not null, base_notes text not null,
  description text not null, image_url text not null, featured boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(brand,name)
);
create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade, product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(), primary key(user_id,product_id)
);
create table if not exists public.reviews (
  id bigint generated by default as identity primary key, user_id uuid references public.profiles(id) on delete set null,
  user_name text not null, rating integer not null check(rating between 1 and 5), comment text not null check(char_length(comment) between 1 and 1000), created_at timestamptz not null default now()
);
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key, user_id uuid references public.profiles(id) on delete set null,
  product_id bigint references public.products(id) on delete set null, product_name text not null, user_name text, user_email text, created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.favorites enable row level security;
alter table public.reviews enable row level security;
alter table public.inquiries enable row level security;
create policy "products are publicly readable" on public.products for select to anon, authenticated using (true);
create policy "reviews are publicly readable" on public.reviews for select to anon, authenticated using (true);
create policy "users read their own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy "users manage their own favorites" on public.favorites for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create index if not exists products_catalog_idx on public.products (brand, gender, category);
create index if not exists favorites_user_idx on public.favorites(user_id);
create index if not exists inquiries_created_idx on public.inquiries(created_at desc);
