-- Production baseline for DREAMS.
-- Safe to apply to a project where the legacy supabase/schema.sql was already run.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  brand text not null,
  name text not null,
  gender text not null check (gender in ('hombre', 'mujer', 'unisex')),
  category text not null default 'diseñador' check (category in ('diseñador', 'nicho')),
  size_ml integer not null check (size_ml > 0),
  price numeric(12, 2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  intensity integer not null check (intensity between 1 and 5),
  family text not null,
  top_notes text not null,
  heart_notes text not null,
  base_notes text not null,
  description text not null,
  image_url text not null,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand, name)
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  user_name text not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  user_name text,
  user_email text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.favorites enable row level security;
alter table public.reviews enable row level security;
alter table public.inquiries enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'products' and policyname = 'products are publicly readable') then
    create policy "products are publicly readable" on public.products for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'reviews' and policyname = 'reviews are publicly readable') then
    create policy "reviews are publicly readable" on public.reviews for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'profiles' and policyname = 'users read their own profile') then
    create policy "users read their own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'favorites' and policyname = 'users manage their own favorites') then
    create policy "users manage their own favorites" on public.favorites for all to authenticated
      using ((select auth.uid()) = user_id)
      with check ((select auth.uid()) = user_id);
  end if;
end
$$;

create or replace function private.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name, role)
  values (
    new.id,
    left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), new.email, 'Cliente'), 80),
    'customer'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function private.create_profile_for_new_user() from public, anon, authenticated;
grant usage on schema private to supabase_auth_admin;
grant usage on schema private to service_role;
grant execute on function private.create_profile_for_new_user() to supabase_auth_admin;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.create_profile_for_new_user();

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public, anon, authenticated;
grant execute on function private.set_updated_at() to service_role;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
  before update on public.products
  for each row execute function private.set_updated_at();

create index if not exists products_catalog_idx on public.products (brand, gender, category);
create index if not exists products_gender_idx on public.products (gender);
create index if not exists products_category_idx on public.products (category);
create index if not exists products_price_idx on public.products (price);
create index if not exists products_featured_idx on public.products (featured desc, id desc);
create index if not exists favorites_user_idx on public.favorites (user_id);
create index if not exists inquiries_created_idx on public.inquiries (created_at desc);
create index if not exists reviews_created_idx on public.reviews (created_at desc);
create index if not exists profiles_created_idx on public.profiles (created_at desc);
