-- Persistent checkout orders and production-ready coupon foundation.
-- Both tables are server-only: the browser must use the Express API.

create table public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_percent numeric(5, 2) not null,
  active boolean not null default true,
  expires_at timestamptz,
  max_uses integer,
  per_user_limit integer,
  minimum_purchase numeric(12, 2),
  conditions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint coupons_code_format check (code = upper(code) and code ~ '^[A-Z0-9_-]{3,40}$'),
  constraint coupons_discount_range check (discount_percent > 0 and discount_percent <= 100),
  constraint coupons_max_uses_positive check (max_uses is null or max_uses > 0),
  constraint coupons_per_user_limit_positive check (per_user_limit is null or per_user_limit > 0),
  constraint coupons_minimum_purchase_positive check (minimum_purchase is null or minimum_purchase >= 0),
  constraint coupons_conditions_object check (jsonb_typeof(conditions) = 'object')
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete restrict,
  provider text not null check (provider in ('mercado_pago')),
  provider_preference_id text,
  provider_payment_id text,
  status text not null default 'created' check (status in ('created', 'approved', 'rejected', 'pending', 'cancelled', 'error')),
  status_detail text check (status_detail is null or char_length(status_detail) <= 160),
  currency text not null default 'ARS' check (currency ~ '^[A-Z]{3}$'),
  subtotal numeric(12, 2) not null check (subtotal >= 0),
  discount numeric(12, 2) not null default 0 check (discount >= 0 and discount <= subtotal),
  total numeric(12, 2) not null check (total >= 0 and total = subtotal - discount),
  coupon_id bigint references public.coupons(id) on delete set null,
  coupon_code text,
  coupon_percent numeric(5, 2),
  items jsonb not null,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_coupon_snapshot check (
    (coupon_code is null and coupon_percent is null and discount = 0)
    or
    (coupon_code = upper(coupon_code) and coupon_percent > 0 and coupon_percent <= 100 and discount > 0)
  ),
  constraint orders_items_array check (jsonb_typeof(items) = 'array' and jsonb_array_length(items) > 0)
);

alter table public.coupons enable row level security;
alter table public.orders enable row level security;

revoke all on table public.coupons from public, anon, authenticated;
revoke all on table public.orders from public, anon, authenticated;
revoke all on sequence public.coupons_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.coupons to service_role;
grant select, insert, update, delete on table public.orders to service_role;
grant usage, select on sequence public.coupons_id_seq to service_role;

drop trigger if exists coupons_set_updated_at on public.coupons;
create trigger coupons_set_updated_at
  before update on public.coupons
  for each row execute function private.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function private.set_updated_at();

create index coupons_active_code_idx on public.coupons (code) where active;
create index coupons_expiry_idx on public.coupons (expires_at) where expires_at is not null;
create index orders_user_created_idx on public.orders (user_id, created_at desc);
create index orders_status_created_idx on public.orders (status, created_at desc);
create index orders_coupon_idx on public.orders (coupon_id) where coupon_id is not null;
create unique index orders_provider_preference_uidx on public.orders (provider, provider_preference_id) where provider_preference_id is not null;
create unique index orders_provider_payment_uidx on public.orders (provider, provider_payment_id) where provider_payment_id is not null;
